#!/bin/sh

# sudo not required for some system commands
for command in reboot ; do
	alias $command="sudo $command"
done; unset command

################
## variables  ##
################

notesDir="$HOME/Documents/notes"

################
##  aliases   ##
################

# use this for ssh as suggested here: https://github.com/kovidgoyal/kitty/issues/713
#alias ssh="kitty +kitten ssh"

# add alias for dotfiles repo
alias config='/usr/bin/git --git-dir=/home/jakob/.cfg/ --work-tree=/home/jakob'

# add alias for nvim 
alias vi='/usr/bin/nvim'

# alias for zathura, opening it always as a new process
alias \
	zathura='zathura --fork' \
	z='zathura --fork' \

# open images scaled to fit viewport
alias feh='feh -.'

# copy current path
alias y.='xclip -selection c <<< $(pwd)'

# cd to content of clipboard
alias cdp='cd $(xclip -selection c -o)'

# start using lecture rofi script
alias lectureRofi='python /usr/local/bin/university-setup-master/scripts/rofi-lectures.py'

# open url of current course
alias oUrl='yq .url ~/current-course/info.yaml | xargs firefox&'

alias cd..="cd .."
alias cd...="cd ../.."
alias cd....="cd ../../.."
alias cd.....="cd ../../../.."
alias cd......="cd ../../../../.."

# aliases for changing directories
# with global flag, to expand with <Ctrl+x a> 
alias -g \
	.C='~/.config' \
	P='~/Documents/Hochschule/Allgemein/Planung' \
	b4='~/Documents/Hochschule/bachelor-4/' \
	O='~/Documents/Code/Odin' \
	N=$notesDir\

# notes
alias notes='nvim $notesDir/index.md'

# todo
alias todo='nvim $notesDir/todo.md'

# tmuxinator
alias mux='tmuxinator'

# taken from luke smith
# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	mkd="mkdir -pv" \

# Colorize commands when possible.
alias \
  ll='ls -l'\
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ip="ip -color=auto"

# delete long entries in history
alias shortenHistory='cat ~/.zhistory | grep -vx ".\{253,500\}" >> ~/.zhistory_shortened'
